### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by zhengguorong** [ccforward/zhihu#1]
npm run start时，提示

Vue packages version mismatch:
- vue@2.0.2
- vue-template-compiler@2.0.3

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader or vueify, re-installing them should bump vue-template-compiler to the latest.

```
at Object.<anonymous> (/Users/zhengguorong/project/feature/zhihu/node_modules/vue-template-compiler/index.js:8:9)
```

**Comment by zhengguorong** [comment]
把package vue版本改为2.0.3即可

**Comment by ccforward** [comment]
@zhengguorong   

好的  我再核对下npm包的版本
