### ISSUE TITLE
auth值问题

### ISSUE THREAD

**Issue by zhengguorong** [ccforward/zhihu#2]
请问config文件里的auth值怎么获取

**Comment by ccforward** [comment]
@zhengguorong 

这个值是从  知乎日报客户端里  抓包获取的

![image](https://cloud.githubusercontent.com/assets/2782664/19752321/fb74da02-9c2e-11e6-84be-333e2d67c585.png)

前提是要登录自己的知乎日报账号

**Comment by zhengguorong** [comment]
你是用mac抓的吗，用了什么工具的

**Comment by ccforward** [comment]
@zhengguorong 

用的 Mac 版本的  Charles 
Windows版本的也有  

Windows  用 Fiddler 也挺好
