### ISSUE TITLE
npm start报错

### ISSUE THREAD

**Issue by aiuluna** [ccforward/zhihu#4]
events.js:160
      throw er; // Unhandled 'error' event
这个怎么处理？？
![qq 20170410143219](https://cloud.githubusercontent.com/assets/14867533/24849359/fadccb6c-1dfd-11e7-9b5b-27b946332406.png)

**Comment by ccforward** [comment]
已经在异常信息里有了提示

没有连接上 mongoDB  

所以你要先开启mongo进程
