### ISSUE TITLE
npm run start 报unhandled error event的错误

### ISSUE THREAD

**Issue by yvonnegithub** [ccforward/zhihu#6]
<img width="618" alt="pic2" src="https://cloud.githubusercontent.com/assets/21054948/25120468/c708fd20-2450-11e7-94ab-9bb42631bcc7.png">

**Comment by ccforward** [comment]
你本地安装了MongoDB没？

**Comment by yvonnegithub** [comment]
安装了
<img width="639" alt="mongo" src="https://cloud.githubusercontent.com/assets/21054948/25120593/6364a8ae-2451-11e7-986d-667316fe4da3.png">

**Comment by ccforward** [comment]
用命令 `mongo`  进入命令行模式

创建数据库
```
use zhihu
```
创建用户 (这里的 username 和 password 要和config.js 里相对应)
```
db.createUser({
  user: "username",
  pwd: "password",
  "roles" : [
  {
    "role" : "readWrite",
    "db" : "report"
  },{
    "role" : "dbAdmin",
    "db" : "report"
  }]
})
```

**Comment by ccforward** [comment]
@yvonnegithub    可以用了吗？

config.js 文件配置过了？

**Comment by yvonnegithub** [comment]
@ccforward 可以启动了，不过启动之后的抓取数据的请求一直在pending是为什么
<img width="892" alt="pending" src="https://cloud.githubusercontent.com/assets/21054948/25122852/fcf7528a-2458-11e7-8867-61cbf36ddc73.png">

**Comment by ccforward** [comment]
![image](https://cloud.githubusercontent.com/assets/2782664/25123403/ca731be4-245a-11e7-993b-fd1b6349fa9b.png)

这个我忘记在README中说明了 

你在config.js文件中设置 `fire: true`  表示开启爬虫，对应的 start  end 为由近到远的日期

`openTask:true` 表示开启定时任务  每日爬虫和定时更新

**Comment by yvonnegithub** [comment]
好的，可以了！
